
INSERT INTO questions_tf
(text, options, chapter, difficulty, book, status, added_by)
VALUES
('Ioan a venit ca martor, ca sa marturiseasca despre Lumina', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 1, 25, 'Ioan', 'Verificat', NULL),
('Ioan a marturisit ca nu a vazut Duhul coborandu-se din cer ca un porumbel', '[{"text": "Adevarat", "correct": false}, {"text": "Fals", "correct": true}]', 1, 50, 'Ioan', 'Verificat', NULL),
('La inceput era Cuvantul si cerurile', '[{"text": "Adevarat", "correct": false}, {"text": "Fals", "correct": true}]', 1, 25, 'Ioan', 'Verificat', NULL),
('Ioan a afirmat despre Isus ca este Mielul lui Dumnezeu care ridica pacatul lumii', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 1, 50, 'Ioan', 'Verificat', NULL),
('Andrei a fost ucenicul care a primit numele de Chifa', '[{"text": "Adevarat", "correct": false}, {"text": "Fals", "correct": true}]', 1, 50, 'Ioan', 'Verificat', NULL),
('In Ioan se afirma ca fratii lui Isus erau la nunta in Cana din Galileea', '[{"text": "Adevarat", "correct": false}, {"text": "Fals", "correct": true}]', 1, 50, 'Ioan', 'Verificat', NULL),
('Iudeii au trimis preoti si leviti sa-l intrebe pe Ioan, in timp ce se afla in Betabara', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 1, 75, 'Ioan', 'Verificat', NULL),
('La nunta erau 6 vase de piatra, in care au pus apa', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 2, 50, 'Ioan', 'Verificat', NULL),
('La nunta erau 5 vase, in care s-a pus apa transformata in vin', '[{"text": "Adevarat", "correct": false}, {"text": "Fals", "correct": true}]', 2, 50, 'Ioan', 'Verificat', NULL),
('Templul a fost construit in 26 de ani, Isus afirma ca il va ridica in doar 3 zile', '[{"text": "Adevarat", "correct": false}, {"text": "Fals", "correct": true}]', 2, 50, 'Ioan', 'Verificat', NULL),
('Nunul nu stia de unde provenea acel vin pe care-l bause la nunta ', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 2, 25, 'Ioan', 'Verificat', NULL),
('Isus a fost instiintat de catre mama sa cu privire la faptul ca nuntasii nu mai au vin sa bea ', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 2, 25, 'Ioan', 'Verificat', NULL),
('Dupa nunta din Cana, Isus a coborat la Capernaum, unde a ramas multe zile. ', '[{"text": "Adevarat", "correct": false}, {"text": "Fals", "correct": true}]', 2, 75, 'Ioan', 'Verificat', NULL),
('Nicodim era un fruntas al iudeilor. ', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 3, 25, 'Ioan', 'Verificat', NULL),
('Nicodim l-a recunoscut pe Isus ca un invatator trimis de Dumnezeu. ', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 3, 25, 'Ioan', 'Verificat', NULL),
('Nicodim era dintre farisei', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 3, 50, 'Ioan', 'Verificat', NULL),
('Pastele iudeilor erau aproape si Isus S-a suit la Ierihon.', '[{"text": "Adevarat", "correct": false}, {"text": "Fals", "correct": true}]', 2, 50, 'Ioan', 'Verificat', NULL),
('Legea a fost data prin Moise', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 1, 25, 'Ioan', 'Verificat', NULL),
('Minunea cu transformarea apei in vin a fost un inceput al semnelor lui Isus', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 2, 25, 'Ioan', 'Verificat', 'olaru_daniel'),
('Isus le-a zis: Stricati templul acesta si in trei zile il voi ridica."', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 2, 25, 'Ioan', 'Verificat', 'olaru_daniel'),
('Isus n-avea trebuinta sa Ii faca cineva marturisiri despre niciun om, pentru ca El stia ce este in om.', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 2, 25, 'Ioan', 'Verificat', 'olaru_daniel'),
('Fiul omului s-a coborat din cer ', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 3, 25, 'Ioan', 'Nou', 'pop_ana'),
('Dumnezeu a trimis pe Fiul Sau ca sa judece lumea ', '[{"text": "Adevarat", "correct": false}, {"text": "Fals", "correct": true}]', 3, 50, 'Ioan', 'Nou', 'pop_ana'),
('Moise a inaltat sarpele pe munte', '[{"text": "Adevarat", "correct": false}, {"text": "Fals", "correct": true}]', 3, 25, 'Ioan', 'Nou', 'pop_ana'),
('Oamenii au iubit mai mult lumina decat intunericul ', '[{"text": "Adevarat", "correct": false}, {"text": "Fals", "correct": true}]', 3, 75, 'Ioan', 'Nou', 'pop_ana'),
('Oricine face raul, nu uraste lumina', '[{"text": "Adevarat", "correct": false}, {"text": "Fals", "correct": true}]', 3, 75, 'Ioan', 'Nou', 'pop_ana'),
('Scaldatoarea Betesda era situata in Ierusalim, langa Poarta Oilor', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 5, 25, 'Ioan', 'Nou', 'jonny'),
('Scaldatoarea Betesda avea 7 pridvoare', '[{"text": "Adevarat", "correct": false}, {"text": "Fals", "correct": true}]', 5, 25, 'Ioan', 'Nou', 'jonny'),
('Slabanogul era paralizat de 20 de ani', '[{"text": "Adevarat", "correct": false}, {"text": "Fals", "correct": true}]', 5, 25, 'Ioan', 'Nou', 'jonny'),
('Iudeii sarbatoreau Pastile ziua cand a fost vindecat slabanogul.', '[{"text": "Adevarat", "correct": false}, {"text": "Fals", "correct": true}]', 1, 50, 'Ioan', 'Nou', 'jonny'),
('Isus a spus: "Adevarat, adevarat va spun ca Fiul nu poate face nimic de la Sine".', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 5, 50, 'Ioan', 'Nou', 'jonny'),
('Tatal nici nu judeca pe nimeni, ci toata judecata a dat-o Fiului.', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 5, 50, 'Ioan', 'Nou', 'jonny'),
('Grecii ziceau deci celui ce fusese vindecat: Este ziua Sabatului, nu-ti este ingaduit sa-ti ridici patul.', '[{"text": "Adevarat", "correct": false}, {"text": "Fals", "correct": true}]', 5, 25, 'Ioan', 'Nou', 'jonny'),
('Isus Se facuse nevazut din norodul care era in locul acela.', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 5, 25, 'Ioan', 'Nou', 'jonny'),
('Carturarii au spus iudeilor ca Isus este Acela care-l facuse sanatos pe slabanog', '[{"text": "Adevarat", "correct": false}, {"text": "Fals", "correct": true}]', 5, 50, 'Ioan', 'Nou', 'jonny'),
('"Iudeii au inceput sa urmareasca pe Isus si cautau sa-L omoare, fiindca facea aceste lucruri in ziua Sabatului."', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 5, 25, 'Ioan', 'Nou', 'jonny'),
('Moise da adevarata paine din cer.', '[{"text": "Adevarat", "correct": false}, {"text": "Fals", "correct": true}]', 6, 25, 'Ioan', 'Nou', 'ungur_mada'),
('Marea Galileii se mai numea si Marea Moarta.', '[{"text": "Adevarat", "correct": false}, {"text": "Fals", "correct": true}]', 6, 25, 'Ioan', 'Nou', 'vele_anca'),
('Isus S-a dus dincolo de Marea Galileii, numita si Marea Tiberiadei.', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 6, 25, 'Ioan', 'Nou', 'vele_anca'),
('Apostolii si cativa oamenii mergeau dupa El.', '[{"text": "Adevarat", "correct": false}, {"text": "Fals", "correct": true}]', 6, 25, 'Ioan', 'Nou', 'vele_anca'),
('O mare gloata mergea dupa El, pentru ca vedea semnele pe care le facea cu cei bolnavi.', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 6, 25, 'Ioan', 'Nou', 'vele_anca'),
('Isus S-a suit pe munte si sedea acolo cu ucenicii Sai.', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 6, 25, 'Ioan', 'Nou', 'vele_anca'),
('Dincolo de paraul Chedron era o gradina in care a intrat Isus cu ucenicii Lui.', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 18, 50, 'Ioan', 'Nou', 'olaru_daniel'),
('Petru a scos sabia si a lovit pe marele preot si i-a taiat urechea dreapta', '[{"text": "Adevarat", "correct": false}, {"text": "Fals", "correct": true}]', 18, 50, 'Ioan', 'Nou', 'olaru_daniel'),
('Petru a scos sabia si a lovit pe robul marelui preot si i-a taiat urechea stanga', '[{"text": "Adevarat", "correct": false}, {"text": "Fals", "correct": true}]', 18, 50, 'Ioan', 'Nou', 'olaru_daniel'),
('Robul marelui preot a carui ureche a fost taiata se numea Malhu', '[{"text": "Adevarat", "correct": true}, {"text": "Fals", "correct": false}]', 18, 25, 'Ioan', 'Nou', 'olaru_daniel');
